---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "archerysec.fullname" . }}-sqldb
  labels:
    app: archerysec
    tier: sqldb
spec:
  selector:
    matchLabels:
      app: archerysec
      tier: sqldb
  serviceName: sqldb
  replicas: {{ .Values.db_replicaCount }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: archerysec
        tier: sqldb
    spec:
      terminationGracePeriodSeconds: 30
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "archerysec.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: postgres
        image: postgres:11
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: sqldb
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        type: {{ .Values.volume_type | default "local"}}
    spec:
      accessModes:
         -  "ReadWriteOnce"
      resources:
        requests:
          storage: {{ .Values.storage_size | default "200M"}}
      volumeName:  {{ .Values.volume_name | default "postgres-pv"}}
      storageClassName:  {{ .Values.storage_class| default "standard"}}

